# -*- coding: utf-8 -*-
"""3task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VYGXp021jPYij7Zj585TOCgpaq15gSXn
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Sample data (replace with your own dataset)
data = pd.DataFrame({
    'cholesterol': ['normal', 'high', 'normal', 'high', 'normal'],
    'gluc': ['normal', 'high', 'normal', 'high', 'high'],
    'alco': [0, 1, 0, 1, 0],
    'active': [1, 1, 0, 0, 1],
    'smoke': [0, 1, 0, 1, 0],
    'cardio': [1, 0, 1, 0, 1]
})

# Create a grid of subplots (2 rows, 3 columns)
g = sns.catplot(
    data=data, kind="count",
    x="cholesterol", hue="cardio",
    palette="Set1", height=3, aspect=2
)
plt.subplots_adjust(top=0.85)  # Adjust the title position
g.fig.suptitle("Cholesterol vs. Cardio", fontsize=16)

# Add titles to subplots
g.axes[0, 0].set_title("Cardio = 0")
g.axes[0, 1].set_title("Cardio = 1")

# Repeat the process for other variables (gluc, alco, active, smoke)
g = sns.catplot(
    data=data, kind="count",
    x="gluc", hue="cardio",
    palette="Set1", height=3, aspect=2
)
plt.subplots_adjust(top=0.85)
g.fig.suptitle("Glucose vs. Cardio", fontsize=16)
g.axes[0, 0].set_title("Cardio = 0")
g.axes[0, 1].set_title("Cardio = 1")

# Repeat for alco, active, and smoke...

# Show the plot
plt.show()